# Generated by Django 5.1 on 2024-10-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
